### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by Llu90** [Anupya/JapaneseTab#1]
Hi! Would love a Firefox version as I can't find one which keeps the frequently visited tabs on. Thank you for your work!

**Comment by xcoineu** [comment]
I didn't learn nothing because it is not talking and I opened 500 tabs until now in chrome. Arigato!

**Comment by Anupya** [comment]
... so you learned something? Either way, this is not the right place. This is only about the Firefox issue - which I am currently working on! Hang tight!

**Comment by Anupya** [comment]
I'm pleased to announce that the Firefox version is out! You can find it here: https://addons.mozilla.org/en-US/firefox/addon/japanesetab/
Please let me know if there any bugs!
