### ISSUE TITLE
Extension is no longer available on the Chrome Store

### ISSUE THREAD

**Issue by naghim** [Anupya/JapaneseTab#10]
Clicking on the Chrome Store link on the GitHub page leads to a 404 page:
![image](https://github.com/user-attachments/assets/42cbdecc-f800-42a4-8220-5c746e44d8b4)

[https://chromewebstore.google.com/detail/japanesetab/jndamehabjcbgopalgabjpplldmjnnfn](https://chromewebstore.google.com/detail/japanesetab/jndamehabjcbgopalgabjpplldmjnnfn)

For those who still want to use it, it's still possible to install the extension using Google Chrome's Developer Mode. By opening the Extensions page on your browser and enabling developer mode, you unlock the ability to load extensions from the file system. To install the extension this way, you must clone the Git repository to your PC and browse to the folder when prompted by the "Load unpacked" button.

Can you please reupload the extension so it may be used again by end users? Thank you!

**Comment by Anupya** [comment]
Thank you for bringing this to my attention, looks like it's been down for 2 years 🙃 It's back up now.

https://chromewebstore.google.com/detail/japanesetab/jndamehabjcbgopalgabjpplldmjnnfn/related
