### ISSUE TITLE
bug: "chinese letter" and "japanese letter" all audios in firefox version

### ISSUE THREAD

**Issue by arkms** [Anupya/JapaneseTab#3]
If i play the audio for any word in the firefox version always say:
"Chine letter" or "Japanese letter".

And thank you, it is a great plugin.

**Comment by Anupya** [comment]
Hey there, glad you like it! I just uninstalled and reinstalled my extension on Firefox and the audio is correct, it does not say "Chine letter" or "Japanese letter". I use the same logic for Firefox and Chrome for audio. Can you check on Chrome and see if it is doing the same thing there?

**Comment by Anupya** [comment]
Hey there! I am now sending the hiragana to audio, instead of kanji (because sometimes kanji is undefined depending on the word, maybe that's what was messing it up?). Let me know if the issue persists. Closing it for now.
