### ISSUE TITLE
[Mobile] Doesn't display values

### ISSUE THREAD

**Issue by jhonatn** [Anupya/JapaneseTab#4]
When used on mobile, it shows a template with placeholder texts, and the wrong scaling.  
I don't know if it should work on mobile, but since it's almost working as of now, it would be awesome that it did.  
Happened on Firefox for Android 66.0.1  

![Screenshot](https://user-images.githubusercontent.com/1548170/54964416-67390b80-4f3a-11e9-8d7a-3dcc9be589dc.jpg)

**Comment by Anupya** [comment]
Hi there! This is a use case I had not considered because I thought like Chrome extensions, Firefox add ons don't work on mobile. I will see if I can fix it. What you are seeing is the pop up when you click on the JapaneseTab icon next to the Chrome address bar.

**Comment by Anupya** [comment]
Hey, unfortunately I am locked out of my Firefox account. Feel free to fork it [https://github.com/Anupya/JapaneseTab-firefox] and load the extension locally. Sorry about that.
