### ISSUE TITLE
Option to hide romaji

### ISSUE THREAD

**Issue by azz** [Anupya/JapaneseTab#5]
I would like to hide the romaji as I find it detrimental to reading Japanese, once you know hiragana you shouldn't ever look at romaji again 😄

**Comment by Anupya** [comment]
Hi there! Your request is 100% valid. However, I made this extension so it helps people learn how to speak Japanese more than reading/writing. I will implement it if I get more requests for this though.

**Comment by clausagerskov** [comment]
submitted an implementation of this

**Comment by Anupya** [comment]
Hey there! After seeing so much interest in this, I implemented it myself. You can now hide romaji! Just click on the Menu icon on the top left.
