### ISSUE TITLE
"Undefined" is displayed when the kanji form doesn't exist

### ISSUE THREAD

**Issue by midse** [Anupya/JapaneseTab#7]
Hello!

Thanks for the great work on this app. :)

When the word doesn't have a kanji reading the app displays "Undefined"  (for example  こそ https://jisho.org/word/%E3%81%93%E3%81%9D). It's a small issue but it would be nice to display the hiragana form only when it occurs!
![Undefined](https://user-images.githubusercontent.com/7143508/56091115-dd31f200-5eaa-11e9-8e4f-0c5f082b7a78.png)

Dimitri

**Comment by Anupya** [comment]
It might look like a glitch if the kanji doesn't appear for some words. I don't like the 'undefined' either but it is a placeholder until I can think of something better. Let me know if you have any suggestions!

**Comment by azz** [comment]
If there is hiragana, just show the hiragana again. Otherwise just show the katakana again.

**Comment by midse** [comment]
> If there is hiragana, just show the hiragana again. Otherwise just show the katakana again.

I agree! It would be really nice. :)

**Comment by Anupya** [comment]
Some words aren't any different in kanji than in hiragana. How would this way differentiate those words? I think replacing kanji with hiragana/katakana versions would make it more confusing.

"Not all hiraganas can be replaced with kanjis": https://www.quora.com/When-do-you-know-to-use-Katakana-Hiragana-and-Kanji-when-writing-in-Japanese

**Comment by midse** [comment]
> Some words aren't any different in kanji than in hiragana. How would this way differentiate those words? I think replacing kanji with hiragana/katakana versions would make it more confusing.
> 
> "Not all hiraganas can be replaced with kanjis": https://www.quora.com/When-do-you-know-to-use-Katakana-Hiragana-and-Kanji-when-writing-in-Japanese

I'm not sure I understand what you're saying.
If we look at the screenshot I posted at the beginning, the word  こそ is never written in Kanji and it's only written in Hiragana. (https://jisho.org/word/%E3%81%93%E3%81%9D)
Displaying at the same time both hiragana and katakana for this word is quite confusing.

You should only display the Hiragana (or Katakana if it's relevant) version of the word when there is no Kanji available.

**Comment by Anupya** [comment]
This is fixed on the latest version! Any undefined fields will be replaced by the hiragana.
