### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by ghost** [Anupya/JapaneseTab#8]
Can you add white background? At least on firefox (66.0.3) if you select one of the colours there is no way to turn it off.

**Comment by Anupya** [comment]
White background was never intended as an option (in both Chrome and Firefox) and you cannot see the white background again even if you delete all site data, cookies and history. I quite like the 4x2 setup right now. However, I will consider adding white background if there is more demand for it.

**Comment by Anupya** [comment]
White background is out!
